version: '3.5'
services:
  pod:
    image: rycus86/podlike
    command: -logs -ipc=false -pull
    labels:
      # proxy container
      pod.component.proxy: |
        image: cloudstateio/cloudstate-proxy-native-dev-mode:latest
        environment:
          - USER_FUNCTION_PORT=8080
          - HTTP_PORT=9000
      # User Function Container
      pod.component.function: |
        image: sleipnir/shopping-cart:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - 9000:9000
