language: rust
cache: cargo
env:
  global:
  - PROJECT_NAME=cloudstate-cli
  - MAKE_DEB=yes
  - DEB_MAINTAINER="Adriano Santos <sleipnir@bsd.com.br>"
  - DEB_DESCRIPTION="Is a lightweight, fast, and fun client that lets you go from
    zero to production with Cloudstate Stateful Serveless functions in minutes"
matrix:
  include:
  - os: osx
    rust: nightly
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: nightly
    env: TARGET=x86_64-unknown-linux-gnu
  allow_failures: 
before_install:
- export PATH="$PATH:$HOME/.cargo/bin"
install:
- bash ci/install.sh
script:
- bash ci/script.sh
before_deploy:
- bash ci/before_deploy.sh
deploy:
  provider: releases
  api_key:
    secure: $github_token
    #secure: g8Gf7FCLRpXSWMGPx5/Pjyozr6hAQA5IhGSIvCIVYTO6TYbjemby8Xuixo8dJXYFxqrET4SVzQVtzg6YX+i46aiB22OX0MhF3HI+2zrtMYDeBECT2ShBmtcgOWF1L0vyKho7wQdzAPkw6V+qzupWtfs12KSLM2wgRT2bv+cnMo3CYYW+V7gWmCMzBmvkmDQgmDOdRvY4Ve8ivLPeZN5klbbGBPfniqebJeTNu8huqkCbabXscRdusSoS4QUouXZXfluHD6rMNP0kykEfHcg8xZNnX6zXhXfbRAYxvLzenXrbbg+HICBEiRaAZ8Woybl25sjIfT72qdW1ImHYvnNfLeja8amw/K5kb/FTXFQp/ocCYgaCffIxLWAt8mIrJeSz+mDDtOqKMomvdQ+jP65VXwBYuZyPBTiwNvfh5+kHesTFkwY8ORemGofXAwQfa1GZqTY5QCqpap7dEsLrdbwEcjSwvmxowLpZIE3sAyW+Z0p2LWyqPEbSV3YU/weTlp6TIi+Qs7hGVzy/TSguWie8ewiH+RRNs+oTNkc/z+fbu/SC8ckk1uMjCDhY05pugMkboVBhFvTPdEmNQSJZ36f4BvCIpsXTUPensY3kFDwHCdlGvRydKHog3pO2+0eFIoOGUF7BxAlA+9OvOyozeuU7ZnY1yFVrygJbxlrSHY0uhDI=
  file: ".travis.yml"
  on:
    repo: sleipnir/cloudstate-cli
    tags: true
branches:
  only:
  - master
  - /\d+\.\d+\.\d+.*$/
notifications:
  email:
    on_success: never
